apiVersion: v1
kind: Service
metadata:
  name: {{ include "minicloud-platform.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: minicloud-api
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
